AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon S3 trigger lambda to unzip a file.
Resources:
  unzipfile:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: >-
        An Amazon S3 trigger lambda to unzip a file.
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::<account number>:<role>'
      Tags:
        project: facturas
